server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_client?useSSL=false
    username: root
    password: '0351'
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.154.138
    virtual-host: /
    username: jacky
    password: '0351'
    port: 5672
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo